-- Migration: Calendar Integration
-- Project: Zhuzh
-- Date: 2026-01-14
-- Description: Add Google Calendar OAuth columns and config tables

-- ============================================
-- Task 1A: Add Google Calendar columns to users table
-- ============================================

-- Add Google Calendar OAuth columns to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS google_calendar_connected BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS google_access_token TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS google_refresh_token TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS google_token_expiry TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS google_calendar_id TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS calendar_connected_at TIMESTAMPTZ;

-- Add index for calendar queries
CREATE INDEX IF NOT EXISTS idx_users_google_calendar ON users(google_calendar_connected) WHERE google_calendar_connected = TRUE;

-- ============================================
-- Task 1B: Create org_calendar_config table
-- ============================================

-- Organization-level calendar detection configuration
-- Generated by Gemini based on admin description + screenshot analysis
CREATE TABLE IF NOT EXISTS org_calendar_config (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,

  -- Detection rules (JSON)
  pto_detection JSONB NOT NULL DEFAULT '{"rules": []}',
  holiday_detection JSONB NOT NULL DEFAULT '{"rules": []}',
  partial_day_detection JSONB NOT NULL DEFAULT '{"patterns": [], "default_hours_deducted": 4}',
  recurring_schedules JSONB NOT NULL DEFAULT '[]',
  shared_calendars JSONB NOT NULL DEFAULT '[]',

  -- Gemini analysis metadata
  confidence_score DECIMAL(3,2) DEFAULT 0.0,
  clarification_questions TEXT[] DEFAULT '{}',
  needs_clarification BOOLEAN DEFAULT FALSE,
  admin_description TEXT,
  screenshot_analysis JSONB,

  -- Audit
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(org_id)
);

-- Enable RLS
ALTER TABLE org_calendar_config ENABLE ROW LEVEL SECURITY;

-- Policy: Admins can manage their org's config
CREATE POLICY "Admins can manage org calendar config" ON org_calendar_config
  FOR ALL USING (
    org_id IN (
      SELECT org_id FROM users WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- Policy: All org members can read config
CREATE POLICY "Org members can read calendar config" ON org_calendar_config
  FOR SELECT USING (
    org_id IN (
      SELECT org_id FROM users WHERE id = auth.uid()
    )
  );

-- ============================================
-- Task 1C: Create user_calendar_events cache table
-- ============================================

-- Cache of user calendar events for quick lookups
-- Refreshed periodically, not on every request
CREATE TABLE IF NOT EXISTS user_calendar_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- Event data
  calendar_id TEXT NOT NULL,
  event_id TEXT NOT NULL,
  summary TEXT,
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  is_all_day BOOLEAN DEFAULT FALSE,

  -- Classification (from Gemini config)
  event_type TEXT CHECK (event_type IN ('pto', 'holiday', 'partial_pto', 'meeting', 'friday_off', 'unknown')),
  classification_confidence DECIMAL(3,2),

  -- Metadata
  raw_event JSONB,
  fetched_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(user_id, event_id)
);

-- Index for date range queries
CREATE INDEX IF NOT EXISTS idx_user_calendar_events_dates
  ON user_calendar_events(user_id, start_time, end_time);

-- Index for type filtering
CREATE INDEX IF NOT EXISTS idx_user_calendar_events_type
  ON user_calendar_events(user_id, event_type) WHERE event_type IS NOT NULL;

-- ============================================
-- Verification query (run after migration):
-- SELECT column_name FROM information_schema.columns
-- WHERE table_name = 'users' AND column_name LIKE 'google%';
-- Should return 6 rows
-- ============================================
