-- ============================================================
-- Calendar Integration Schema
-- Run this in Supabase SQL Editor
-- ============================================================

-- Add calendar columns to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS google_calendar_connected BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS google_access_token TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS google_refresh_token TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS google_token_expiry TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS google_calendar_id TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS calendar_connected_at TIMESTAMPTZ;

-- Organization calendar configuration (generated by Gemini)
CREATE TABLE IF NOT EXISTS org_calendar_config (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID REFERENCES organizations(id) NOT NULL,
  
  -- Detection rules (JSON from Gemini analysis)
  pto_detection JSONB DEFAULT '{}',
  holiday_detection JSONB DEFAULT '{}',
  partial_day_detection JSONB DEFAULT '{}',
  recurring_schedules JSONB DEFAULT '[]',
  
  -- Identified shared calendars
  shared_calendars JSONB DEFAULT '[]',
  holiday_calendars JSONB DEFAULT '[]',
  
  -- Admin input that generated this config
  admin_description TEXT,
  admin_screenshots TEXT[],
  
  -- Confidence and status
  confidence_score NUMERIC(3,2),
  needs_clarification BOOLEAN DEFAULT FALSE,
  clarification_questions JSONB DEFAULT '[]',
  
  -- Audit
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by UUID REFERENCES users(id),
  
  UNIQUE(org_id)
);

-- Cache of calendar events (refreshed periodically)
CREATE TABLE IF NOT EXISTS calendar_events_cache (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id) NOT NULL,
  calendar_id TEXT NOT NULL,
  event_id TEXT NOT NULL,
  
  summary TEXT,
  start_time TIMESTAMPTZ,
  end_time TIMESTAMPTZ,
  is_all_day BOOLEAN DEFAULT FALSE,
  
  -- Detection results
  detected_as TEXT,
  confidence NUMERIC(3,2),
  
  -- Raw event data
  raw_event JSONB,
  
  fetched_at TIMESTAMPTZ DEFAULT NOW(),
  
  UNIQUE(user_id, calendar_id, event_id)
);

-- Index for quick lookups
CREATE INDEX IF NOT EXISTS idx_calendar_events_user_time 
ON calendar_events_cache(user_id, start_time, end_time);

-- Index for PTO detection queries
CREATE INDEX IF NOT EXISTS idx_calendar_events_detected 
ON calendar_events_cache(user_id, detected_as, start_time);

-- ============================================================
-- RLS Policies (optional, enable when ready for production)
-- ============================================================

-- Users can only see their own calendar data
-- ALTER TABLE calendar_events_cache ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY calendar_events_user_policy ON calendar_events_cache
--   FOR ALL USING (user_id = auth.uid());

-- Org config visible to org members
-- ALTER TABLE org_calendar_config ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY org_calendar_config_policy ON org_calendar_config
--   FOR SELECT USING (
--     org_id IN (SELECT org_id FROM users WHERE id = auth.uid())
--   );
-- CREATE POLICY org_calendar_config_admin_policy ON org_calendar_config
--   FOR ALL USING (
--     EXISTS (
--       SELECT 1 FROM users 
--       WHERE id = auth.uid() 
--       AND org_id = org_calendar_config.org_id 
--       AND role IN ('admin', 'manager')
--     )
--   );
